### ISSUE TITLE
RFC

### ISSUE THREAD

**Issue by casperdcl** [0x2b3bfa0/cml-use-case-matrix-cloud#1]
would be great to replace:

https://github.com/0x2b3bfa0/cml-use-case-matrix-cloud/blob/0c838f88fe57090fd8dfdad49514cbc24f728dfc/.github/workflows/cml.yml#L9-L30

with:

```yaml
       - id: matrix
         uses: iterative/cml-matrix@v1
         with:
           json: matrix.json
```

or even:

```yaml
       - id: matrix
         run: cml matrix --json=matrix.json
```

unfortunately [GL has a significantly different way of doing things](https://about.gitlab.com/blog/2020/04/24/parent-child-pipelines/#dynamically-generating-pipelines) so it's not portable (it's GH-specific) but is clean...

/CC @0x2b3bfa0 @DavidGOrtega
